In [1]:
import pandas as pd
import numpy as np

reading the mean_1:

In [16]:
Ds1_m1= pd.read_csv("hwk2_datasets/DS1_m_1.txt", header = None)
Ds1_m1 = Ds1_m1.to_numpy()
Ds1_m1 = Ds1_m1[0][:20]
print(f'the first mean matrix{Ds1_m1}')

the first mean matrix[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]

reading the mean_0:

In [17]:
Ds1_m0= pd.read_csv("hwk2_datasets/DS1_m_0.txt", header = None)
Ds1_m0 = Ds1_m0.to_numpy()
Ds1_m0 = Ds1_m0[0][:20]
print(f'the zero mean matrix{Ds1_m0}')

the zero mean matrix[1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.3
 1.3 1.3]

reading the covariance matrix:

In [18]:
Ds1_cov= pd.read_csv("hwk2_datasets/DS1_Cov.txt", header = None)
Ds1_cov
Ds1_cov = Ds1_cov.to_numpy()
Ds1_cov = Ds1_cov[:, :20]
print(f'the covariance matrix{Ds1_cov}')

the covariance matrix[[7.92747613 5.48849335 6.18812365 5.17766549 5.84803095 6.15325514
  4.6623167  5.45500286 4.98574312 5.18758586 3.9436397  5.26132514
  7.09637106 5.99810181 6.0932167  5.99518462 5.87317499 5.70538764
  5.59907089 5.91786273]
 [5.48849335 6.81598145 5.34490996 4.31020106 5.41645238 5.53995027
  4.30811201 3.93658438 4.11429237 4.98428213 3.34393835 4.59050685
  5.85714703 5.07764986 5.41356597 5.19974264 5.60959615 5.09170926
  5.31814733 5.27567458]
 [6.18812365 5.34490996 7.322937   4.87361613 5.78994181 6.60647915
  4.61175555 4.83989875 4.86905732 5.05339559 3.26344459 4.68117364
  6.36913218 5.17240371 6.107158   5.99640412 6.24914837 4.99487173
  4.72323191 5.0810024 ]
 [5.17766549 4.31020106 4.87361613 5.77060116 5.26312518 4.50414113
  3.70666948 4.39831182 3.37569889 4.20589158 2.74695007 4.1714241
  5.86605885 4.78774458 4.78672203 5.08695389 4.67678137 4.57195323
  3.91537274 5.75972062]
 [5.84803095 5.41645238 5.78994181 5.26312518 7.01239219 5.39143047
  5.00679847 4.38069986 4.64759399 5.11560693 4.07101072 4.99248684
  6.2216833  5.83054834 5.95588404 6.17991278 5.89633465 5.15754486
  5.35690654 5.72019074]
 [6.15325514 5.53995027 6.60647915 4.50414113 5.39143047 6.73659871
  4.45649259 4.90819445 4.73391895 5.30643771 2.98349649 4.82631716
  6.37875695 4.98412722 5.80736823 6.00013022 5.93975039 4.99010068
  4.79687342 5.19390579]
 [4.6623167  4.30811201 4.61175555 3.70666948 5.00679847 4.45649259
  5.15327816 3.89248991 3.94043875 4.32608261 2.98887118 4.33684719
  4.6987155  4.12621678 4.69532302 5.26589859 4.31675998 3.68245247
  4.60214716 3.8718588 ]
 [5.45500286 3.93658438 4.83989875 4.39831182 4.38069986 4.90819445
  3.89248991 6.02421683 3.57582001 4.90028608 2.53175277 4.87397837
  6.17340907 5.18646095 4.9062092  6.17541256 4.53542361 4.93591903
  4.82770474 4.49208748]
 [4.98574312 4.11429237 4.86905732 3.37569889 4.64759399 4.73391895
  3.94043875 3.57582001 4.93819672 4.622955   3.10824518 4.07317558
  5.07802813 4.62466362 4.88140573 5.11636804 5.10593429 4.06190408
  4.21466406 4.04194538]
 [5.18758586 4.98428213 5.05339559 4.20589158 5.11560693 5.30643771
  4.32608261 4.90028608 4.622955   7.05196469 3.27078036 4.70649653
  6.80870714 5.16872023 4.98485588 5.95197592 4.7432323  5.27218812
  4.51770864 5.2901418 ]
 [3.9436397  3.34393835 3.26344459 2.74695007 4.07101072 2.98349649
  2.98887118 2.53175277 3.10824518 3.27078036 3.32925254 2.88538599
  3.71248416 3.88910195 3.57770032 3.63856611 3.61658951 3.19715094
  3.71649378 3.44846334]
 [5.26132514 4.59050685 4.68117364 4.1714241  4.99248684 4.82631716
  4.33684719 4.87397837 4.07317558 4.70649653 2.88538599 5.26795827
  6.00123918 5.00792617 4.81447736 5.56166685 5.04940488 4.88317354
  5.02705151 4.48212019]
 [7.09637106 5.85714703 6.36913218 5.86605885 6.2216833  6.37875695
  4.6987155  6.17340907 5.07802813 6.80870714 3.71248416 6.00123918
  9.05303755 6.27727968 6.23240739 6.57061448 6.00662195 6.34972468
  5.87165804 7.25375353]
 [5.99810181 5.07764986 5.17240371 4.78774458 5.83054834 4.98412722
  4.12621678 5.18646095 4.62466362 5.16872023 3.88910195 5.00792617
  6.27727968 6.90345861 5.85117855 6.21468055 5.6886307  5.61334089
  5.87982214 5.45148242]
 [6.0932167  5.41356597 6.107158   4.78672203 5.95588404 5.80736823
  4.69532302 4.9062092  4.88140573 4.98485588 3.57770032 4.81447736
  6.23240739 5.85117855 6.94254049 7.13848616 5.82374197 5.12770585
  5.45990133 5.688824  ]
 [5.99518462 5.19974264 5.99640412 5.08695389 6.17991278 6.00013022
  5.26589859 6.17541256 5.11636804 5.95197592 3.63856611 5.56166685
  6.57061448 6.21468055 7.13848616 9.27652805 5.86248831 5.8938436
  5.65844133 5.86034762]
 [5.87317499 5.60959615 6.24914837 4.67678137 5.89633465 5.93975039
  4.31675998 4.53542361 5.10593429 4.7432323  3.61658951 5.04940488
  6.00662195 5.6886307  5.82374197 5.86248831 6.75920034 5.19311847
  5.32663333 4.94557014]
 [5.70538764 5.09170926 4.99487173 4.57195323 5.15754486 4.99010068
  3.68245247 4.93591903 4.06190408 5.27218812 3.19715094 4.88317354
  6.34972468 5.61334089 5.12770585 5.8938436  5.19311847 5.96390927
  4.84794484 5.12375508]
 [5.59907089 5.31814733 4.72323191 3.91537274 5.35690654 4.79687342
  4.60214716 4.82770474 4.21466406 4.51770864 3.71649378 5.02705151
  5.87165804 5.87982214 5.45990133 5.65844133 5.32663333 4.84794484
  6.35142867 4.89494004]
 [5.91786273 5.27567458 5.0810024  5.75972062 5.72019074 5.19390579
  3.8718588  4.49208748 4.04194538 5.2901418  3.44846334 4.48212019
  7.25375353 5.45148242 5.688824   5.86034762 4.94557014 5.12375508
  4.89494004 7.88428428]]

generate data from multivariate Gaussian distribution with Ds1_m1 as mean and Ds1_cov as covariance and label this data to be porisitve( Y = 1)

In [19]:
data_positive = np.random.multivariate_normal(Ds1_m1, Ds1_cov, 2000)

ones = np.ones((2000,1))
data_positive = np.append(data_positive, ones, axis=1)


data_positive_pd = pd.DataFrame(data_positive)
data_positive_pd.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.888040,2.028956,-0.691627,0.381560,-1.344707,0.929363,-0.575512,2.064419,0.713438,2.667403,...,1.762272,2.884086,-1.324056,0.046844,1.839731,0.332765,0.644488,0.000968,2.996812,1.0
1,-1.061575,-1.371096,-2.123324,-0.472337,-1.314931,-2.105384,-0.797719,0.422715,0.474378,-0.571392,...,-0.097068,-1.026905,1.513566,0.239463,0.203904,-0.989245,0.153732,0.665495,-0.177369,1.0
2,-0.817504,0.166950,-0.992777,-0.014112,-0.327971,0.948569,0.232848,0.601897,-0.316640,1.265910,...,1.430956,1.100382,-2.140137,0.152642,1.099001,-1.133693,0.617614,-1.300501,0.729548,1.0
3,1.155765,1.775966,0.386802,-0.620402,-2.341406,1.712480,-0.336216,1.545044,1.872783,1.560825,...,0.366951,-0.141975,0.715620,0.241263,1.104452,1.405960,1.000331,0.813560,0.331216,1.0
4,5.887436,4.484024,6.299026,7.162160,5.477135,6.631512,4.283084,7.977947,4.028843,6.193883,...,4.926000,7.058069,7.035786,6.646060,9.696360,4.623695,6.158579,4.799312,8.244693,1.0

generate data from multivariate Gaussian distribution with Ds1_m0 as mean and Ds1_cov as covariance and label this data to be negative( Y = 0)

In [21]:
data_negative = np.random.multivariate_normal(Ds1_m0, Ds1_cov, 2000)

ones = 0 * np.ones((2000,1))
data_negative = np.append(data_negative, ones, axis=1) 


data_negative_pd = pd.DataFrame(data_negative)
data_negative_pd.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,6.101319,3.651888,7.446212,3.745638,5.246607,6.476794,1.918129,3.060505,5.993963,3.226263,...,3.453665,6.702014,3.713031,6.128970,2.530799,6.744071,2.508930,2.810909,3.695988,0.0
1,2.476914,3.898031,2.416095,1.129108,2.101649,1.373892,2.580396,-0.535333,1.549252,1.504119,...,0.143127,1.992128,0.678440,1.810009,-0.105299,1.084832,1.058696,2.201895,2.773101,0.0
2,0.145243,-0.705602,-0.683132,1.182237,-1.775170,-0.837847,-0.760374,-1.023505,-0.873119,0.186464,...,-0.152956,0.549468,-1.743064,-4.447877,-6.494803,-1.492336,-0.944229,-2.581483,-0.244795,0.0
3,-2.504146,-0.558224,0.009083,0.919894,0.471464,-0.743057,1.076414,0.692558,0.045394,-0.494944,...,1.389440,0.815948,-0.915794,1.728687,3.084961,0.048150,-0.701853,0.171220,1.279514,0.0
4,0.707124,1.735091,2.949663,1.884900,-0.963404,2.494731,0.687648,2.285841,2.795784,4.424758,...,-0.210157,2.839947,0.305303,2.590956,2.158878,1.295574,0.622847,-0.352529,1.675367,0.0

pick the train and test and validation data based on the percent in assignment and also pick the data randomly without replacement( by shuffling the data at the first step)

In [22]:
np.random.shuffle(data_positive)
data_positive_train = data_positive[0:1200]
data_positive_test = data_positive[1200:1600]
data_positive_valid = data_positive[1600:2000]

In [23]:
np.random.shuffle(data_negative)
data_negative_train = data_negative[0:1200]
data_negative_test = data_negative[1200:1600]
data_negative_valid = data_negative[1600:2000]

In [24]:
data_test = np.concatenate((data_positive_test, data_negative_test))
data_train = np.concatenate((data_positive_train, data_negative_train))
data_valid = np.concatenate((data_positive_valid, data_negative_valid))

In [25]:
np.random.shuffle(data_test)
np.random.shuffle(data_train)
np.random.shuffle(data_valid)

In [27]:
print(f'shape of train data{data_train.shape}')
print(f'shape of test data{data_test.shape}')
print(f'shape of validation data{data_valid.shape}')

shape of train data(2400, 21)
shape of test data(800, 21)
shape of validation data(800, 21)

save the test and train and validation data to the repository

In [31]:
np.savetxt('DS1_train.csv', data_train, delimiter=',')
np.savetxt('DS1_test.csv', data_test, delimiter=',')
np.savetxt('DS1_valid.csv', data_valid, delimiter=',')

save the entire datasets to the repository and save it as DS1

In [41]:
data = np.concatenate((data_train, data_test, data_valid))
np.savetxt('DS1.csv', data, delimiter=',')

In [44]:
data_pd = pd.DataFrame(data)
data_pd.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.239545,0.157858,0.317379,2.325290,1.085985,0.615187,0.801917,-0.377311,0.743906,1.495590,...,-0.081254,1.869578,0.414248,0.837193,-1.318078,-0.246449,-0.120056,0.372897,3.980492,1.0
1,-4.326049,-6.387349,-3.432464,-2.273022,-5.920508,-3.791945,-2.831020,-1.553234,-5.246149,-4.539817,...,-4.558090,-5.381166,-6.102075,-5.030490,-1.674091,-6.687805,-4.163242,-5.734088,-2.324974,0.0
2,1.400250,-0.232560,0.927250,0.416738,0.554625,0.665925,0.893217,1.524083,1.889068,1.655013,...,0.838584,0.302490,1.205353,1.692584,2.577223,0.044770,1.382098,-0.562667,-1.151597,1.0
3,1.070849,1.965054,2.029255,0.248081,2.091488,2.926687,1.007712,-0.577580,3.082080,3.929003,...,0.555572,2.376210,0.148513,2.412705,2.864776,1.542954,1.967172,-0.330396,3.058014,0.0
4,3.094258,1.334980,4.671363,2.883454,4.182638,4.095993,2.290213,3.827606,4.201037,2.235943,...,1.901344,2.063795,5.689429,4.477883,4.670311,4.668107,2.666326,3.281577,2.110554,0.0

write the data in text file follow the instruction

In [51]:
np.savetxt('Assignment2_2122841_1_1_DS1.txt', data, newline='\n', delimiter=',')
np.savetxt('Assignment2_2122841_1_1_DS1_train.txt', data_train, newline='\n', delimiter=',')
np.savetxt('Assignment2_2122841_1_1_DS1_test.txt', data_test, newline='\n', delimiter=',')
np.savetxt('Assignment2_2122841_1_1_DS1_valid.txt', data_valid, newline='\n', delimiter=',')